language: node_js
node_js: "7"
cache: yarn
script:
  # Check that linting does not modify files. If yes, that means the project wasn't properly linted.
  - yarn run lint && git diff-files --quiet
  - yarn test
