language: node_js
node_js: "8"
branches:
  only:
    - master
before_script:
  - npm install -g now
script:
  - ci/build.sh
  - url=$(ci/deploy.sh)
  - ci/e2e-test.sh $url
after_success:
  - ci/promote.sh $url
